### ISSUE TITLE
More exact model for frequency-domain forward pass

### ISSUE THREAD

**Issue by tomato18463** [fjiang9/NKF-AEC#3]
Hi,

Thank you for your great project. I have a question about the frequency-domain forward pass in your paper/code. I note your model simply multiplies stft of input signal and filter weights, and the result is an approximation of time-domain convolution. I wonder if you have tried any exact frequency-domain forward pass models, such as overlap saving? And if yes, what's its effect on the performance?

Thanks

**Comment by fjiang9** [comment]
@tomato18463 Thanks for your attention. I've also briefly tried the partitioned-block-based frequency-domain Kalman filtering (PBFDKF) based NKF-AEC, but could only get much worse results than the NKF reported in our paper. Maybe you can do such experiments by yourself, and don't forget to tell me your findings : )
