### ISSUE TITLE
Some problems on real sequences.

### ISSUE THREAD

**Issue by c8x1** [fjiang9/NKF-AEC#6]
I tried to reproduce your results, but I found that there are two phenomena (bad results) in some real sequences, both of which also appear in the model you provide.
1. may be that the filter diverges (the estimated echo energy is unusually high);
2. the estimated echo have a howling-like sound (which doesnt exist in the reference signal);
Most of these two happens at the beginning of the sentence(but not necessarily at the beginning of the sequence).

Did you find anything like this?

**Comment by fjiang9** [comment]
@c8x1 Could you provide the test audio samples you used?

**Comment by c8x1** [comment]
sry i cant provide them because of privacy reasons. its just some real captured audio.  But the audio itself is not special. I blame it on the lack of stability of the filter, maybe some post-processing.
