### ISSUE TITLE
why put self.kg_net.init_hidden in the NKF forward function?

### ISSUE THREAD

**Issue by xiaoqi91** [fjiang9/NKF-AEC#7]
could you please explain that why did you put the init step "self.kg_net.init_hidden(B * F, device)" in the forward function of class NKF? This will put gru weights to be zero, is it OK when training ?

**Comment by fjiang9** [comment]
@xiaoqi91 Sure, it is okay as long as you call the init_hidden function before the Kalman filtering iteration.

**Comment by xiaoqi91** [comment]
> @xiaoqi91 Sure, it is okay as long as you call the init_hidden function before the Kalman filtering iteration.

thank you for your reply! one more question, there is only one complex gru layer in file src/nkf.py, but the paper writes that the model consists of one complex fully-connected (FC) layer, two complex GRU layers, and another two complex FC layers.  they seem to be inconsistent. . .could you please explain this question?

**Comment by fjiang9** [comment]
@xiaoqi91 Oops, it should be a typo. Only one complex GRU layer is used in the paper.

**Comment by xiaoqi91** [comment]
> @xiaoqi91 Oops, it should be a typo. Only one complex GRU layer is used in the paper.

ok, thank you !
