### ISSUE TITLE
I found that the cost of NKF is a little bit huge.

### ISSUE THREAD

**Issue by c8x1** [fjiang9/NKF-AEC#8]
Although the number of parameters is small, the cost of NKF is a little bit high, especially as the number of taps increases. Have you completed the model deployment on the actual device? Do you have any ideas for simplifying the model?

**Comment by fjiang9** [comment]
Yes, although the computational cost of NKF is much less than other NN-based AEC models, we still think it can be furthur reduced. We plan to work on that in the near future.
