### ISSUE TITLE
Question about the training dataset

### ISSUE THREAD

**Issue by cd-zlm** [fjiang9/NKF-AEC#9]
Hi there, thank you  for providing such a good project . I tested your pre-train model and found it work well in my real recording data, and I was wondering how many hours data did you used in train your model , thanks!

**Comment by fjiang9** [comment]
Thanks for your attention! The pretrained model provided in this repository is trained using the data discribed in our paper.

**Comment by shenbuguanni** [comment]
> Hi there, thank you for providing such a good project . I tested your pre-train model and found it work well in my real recording data, and I was wondering how many hours data did you used in train your model , thanks!

Please ask if you reproduced the training of this model
